const sentences = [
  "So when she was a sickly, fretful, ugly little baby she was kept out of the way, and when she became a sickly, fretful, toddling thing she was kept out of the way also.",
  "She was grinding her teeth and saying this over and over again when she heard her mother come out on the veranda with some one.",
  "The noise and hurrying about and wailing over the cholera had frightened her, and she had been angry because no one seemed to remember that she was alive.",
  "If she had been older she would no doubt have been very anxious at being left alone in the world, but she was very young, and as she had always been taken care of, she supposed she always would be.",
  "She was watching the passing buses and cabs and people, but she heard quite well and was made very curious about her uncle and the place he lived in.",
  "If the pretty wife had been alive she might have made things cheerful by being something like her own mother and by running in and out and going to parties as she had done in frocks full of lace.",
  'Martha had buttoned up" her little sisters and brothers but she had never seen a child who stood still and waited for another person to do things for her as if she had neither hands nor feet of her own.',
  "When she went into the room which had been made into a nursery for her, she found that it was rather like the one she had slept in.",
  "There, she found more walls and winter vegetables and glass frames, but in the second wall there was another green door and it was not open.",
  "She ran only to make herself warm, and she hated the wind which rushed at her face and roared and held her back as if it were some giant she could not see.",
  "she cried out, pattering down the walk; and she chirped and tried to whistle, which last she did not know how to do in the least.",
  "She always stopped to look at the children, and wonder what their names were, and where they had gone, and why they wore such odd clothes.",
  "It seemed as if there was no one in all the huge rambling house but her own small self, wandering about upstairs and down, through narrow passages and wide ones, where it seemed to her that no one but herself had ever walked.",
  "A broad window with leaded panes looked out upon the moor; and over the mantel was another portrait of the stiff, plain little girl who seemed to stare at her more curiously than ever.",
  "In all her wanderings through the long corridors and the empty rooms, she had seen nothing alive; but in this room she saw something.",
  "She was going to walk five miles across the moor to the cottage, and she was going to help her mother with the washing and do the week's baking and enjoy herself thoroughly.",
  "His red waistcoat was like satin and he puffed his tiny breast out and was so fine and so grand and so pretty that it was really as if he were showing her how important and like a human person a robin could be.",
  "Living as it were, all by herself in a house with a hundred mysteriously closed rooms and having nothing whatever to do to amuse herself, had set her inactive brain to working and was actually awakening her imagination.",
  "Her mother had been glad to see her and they had got the baking and washing all out of the way.",
  "She counted and skipped, and skipped and counted, until her cheeks were quite red, and she was more interested than she had ever been since she was born.",
  "Mary had thought it must be different from other gardens which had not been left all by themselves so long; and indeed it was different from any other place she had ever seen in her life.",
  "But she was inside the wonderful garden and she could come through the door under the ivy any time and she felt as if she had found a world all her own.",
  "All that troubled her was her wish that she knew whether all the roses were dead, or if perhaps some of them had lived and might put out leaves and buds as the weather got warmer.",
  "The exercise made her so warm that she first threw her coat off, and then her hat, and without knowing it she was smiling down on to the grass and the pale green points all the time.",
  "He answered every one of them in his queer grunting way and he did not seem really cross and did not pick up his spade and leave her.",
  "She went skipping slowly down the outside walk, thinking him over and saying to herself that, queer as it was, here was another person whom she liked in spite of his crossness.",
  "She enjoyed the skipping very much and when she reached the little gate she opened it and went through because she heard a low, peculiar whistling sound and wanted to find out what it was.",
  "As she came closer to him she noticed that there was a clean fresh scent of heather and grass and leaves about him, almost as if he were made of them.",
  "She liked it very much and when she looked into his funny face with the red cheeks and round blue eyes she forgot that she had felt shy.",
  "He told her what they looked like when they were flowers; he told her how to plant them, and watch them, and feed and water them.",
  "Then she crept across the room, and, as she drew nearer, the light attracted the boy's attention and he turned his head on his pillow and stared at her, his gray eyes opening so wide that they seemed immense.",
  "She felt almost sure that if she kept on talking and could make him see the garden in his mind as she had seen it he would like it so much that he could not bear to think that everybody might tramp in to it when they chose.",
  'That is nice," he said more drowsily still, and she went on chanting and stroking, but when she looked at him again his black lashes were lying close against his cheeks, for his eyes were shut and he was fast asleep.',
  "There were rich colors in the rugs and hangings and pictures and books on the walls which made it look glowing and comfortable even in spite of the gray sky and falling rain.",
  "It will make the green points push up and up and up, and it will make the bulbs and roots work and struggle with all their might under the earth.",
  "There were things sprouting and pushing out from the roots of clumps of plants and there were actually here and there glimpses of royal purple and yellow unfurling among the stems of crocuses.",
  "It's the best thing that could happen to the sickly pampered thing to have some one to stand up to him that's as spoiled as himself;\" and she laughed into her handkerchief again.",
  "She had looked forward to telling him a great many things and she had meant to try to make up her mind whether it would be safe to trust him with the great secret.",
  "Doors were opened and shut and there were hurrying feet in the corridors and some one was crying and screaming at the same time, screaming and crying in a horrible way.",
  "He had not felt embarrassed because the crow had not known his language and had only stared and had not spoken to him the first time they met.",
  "He had lived on a sort of desert island all his life and as he had been the king of it he had made his own manners and had had no one to compare himself with.",
  "If you have never had a garden you cannot understand, and if you have had a garden you will know that it would take a whole book to describe all that came to pass there.",
  "Satiny poppies of all tints danced in the breeze by the score, gaily defying flowers which had lived in the garden for years and which it might be confessed seemed rather to wonder how such new people had got there.",
  "He had made himself believe that he was going to get well, which was really more than half the battle, if he had been aware of it.",
  "It was a curiously entertaining morning and the feeling of wandering about in the same house with other people but at the same time feeling as if one were miles away from them was a fascinating thing.",
  "A terrible sorrow had fallen upon him when he had been happy and he had let his soul fill itself with blackness and had refused obstinately to allow any rift of light to pierce through.",
  "He had been on the tops of mountains whose heads were in the clouds and had looked down on other mountains when the sun rose and touched them with such light as made it seem as if the world were just being born.",
  "He did not know how long he sat there or what was happening to him, but at last he moved as if he were awakening and he got up slowly and stood on the moss carpet, drawing a long, deep, soft breath and wondering at himself.",
  "He had refused to see it, and when he had gone to look at it at last it had been, such a weak wretched thing that everyone had been sure it would die in a few days.",
  'All this was not an uplifting thing to recall, but as the train whirled him through mountain passes and golden plains the man who was coming alive" began to think in a new way and he thought long and steadily and deeply.',
  "Craven had extended them just in time to save him from falling as a result of his unseeing dash against him, and when he held him away to look at him in amazement at his being there he truly gasped for breath.",
  "There is a sort of a something about that kind of house that makes you hardly able even to talk to each other when you are left alone, and playing seems unnatural and affected.",
  "Away across the grassy slopes deer were feeding, and in the distance where the groves of trees thickened into what looked almost a forest were enormous shapes of grey stone, like nothing that the children had ever seen before.",
  "The arm wore a sleeve of pink and gold brocaded silk, faded a little here and there but still extremely imposing, and the sleeve was part of a dress, which was worn by a lady who lay on the stone seat asleep in the sun.",
  "I couldn't find anything but bread and cheese but it doesn't matter, because everything's magic here, and unless you have some dreadful secret fault the bread and cheese will turn into anything you like.",
  'Hold it steady," she said, and undid the shutters of a long window, so that first a yellow streak and then a blazing great oblong of light flashed at them and the room was full of sunshine.',
  "It was rather horrid to see the bread and butter waving about in the air, and bite after bite disappearing from it apparently by no human agency; and the spoon rising with apple in it and returning to the plate empty.",
  "Kathleen put out the gas and got into bed; all this magic had been rather upsetting, and she was just the least bit frightened, but in the dark she found it was not so bad.",
  "You can, in fact, almost always tell whether the thing has been found that people have gone to look for by the sound of their feet as they return.",
  "Eliza, once convinced that her chest, though invisible, was not transparent, and that her companions could not by looking through it count how many buns she had eaten, made an excellent meal.",
  "There are some days like that, you know, when everything goes well from the very beginning; all the things you want are in their places, nobody misunderstands you, and all that you do turns out admirably.",
  "He did not know how near she was to the scream that would throw away the whole thing and bring the police and the residents out to the ruin of everybody.",
  "and crossed the road hurriedly; and when, next day, he told what he had seen, his wife disbelieved him, and also said it was a judgement on him, which was unreasonable.",
  "And the horrible thing was that though they could see it happening they did not know what was happening, and could not have stopped it if they had.",
  'They say in our office," said the boy, paying for the bun honourably with unasked information, "as these two is all for cutting each other\'s throats oh, only in the way of business been at it for years.',
  "Gerald felt sick and giddy, and there was something at the back of his mind that he knew would make him feel sicker and giddier as soon as he should have the sense to remember what it was.",
  "Mabel being the size she was now it would be quite difficult not to step on some part or other of her, if she should happen to be in one's way quite difficult, however much one tried.",
  "One could see that they were only reflections by the way their shape broke and changed as the gold and silver fish rippled the water with moving fin and tail that steered.",
  "You have beheld us because you held the ring, and are of one brotherhood with us in your marble, but on that one night all may behold us.",
  "And those who listened forgot time and space, and how to be sad, and how to be naughty, and it seemed that the whole world lay like a magic apple in the hand of each listener, and that the whole world was good and beautiful.",
  "But presently the passage took a turn, there were more steps, down, down, and then the passage was empty and straight lined above and below and on each side with slabs of marble, very clear and clean.",
  "Those pink and purple hats are nodding off in the distant prospect; and the funny little man with the beard like a goat is going a different way from everyone else the gardeners will have to head him off.",
  "I am sure you must all have noticed this when you are going out to tea anywhere in your best clothes, especially if your clothes are starched and you happen to have a rather long and shadeless walk.",
  "They had almost reached that stage of resentment and discomfort when one wishes one hadn't come\" before they saw, below the edge of the beechwood, the white waved handkerchief of the bailiff.",
  "The moonbeam slants more and more; now it touches the far end of the stone, now it draws nearer and nearer to the middle of it, now at last it touches the very heart and centre of that central stone.",
  "Yet now no one spoke a word, because all had come into the circle of the real magic where all things are understood without speech.",
  "She had fair hair, it is true, and it was plaited in two braids, but they were very long and straight; she herself was long and lean and had a freckled face and bright, jolly eyes.",
  "He turned and went again towards the city, and when he was close to it he gave a little cry, hastily stifled, for fear some one should hear him and come down and send him to bed.",
  "On the other hand, it was the only thing that seemed to lead anywhere, and he had had enough of standing lonely in the grassy prairie, where he seemed to have been for a very long time indeed.",
  "It was not daylight yet, and the room, large and bare, with an arch at each end and narrow little windows at the sides, was lighted by horn lanterns and tall tapers in pewter candlesticks.",
  "For years and years and years there's been a guard here, because when the town was first built the astrologers foretold that some day there would be a trespasser who would do untold mischief.",
  "He could see the flat feet of the nurse and the lower part of her grey skirt, and a rattling and rumbling on the table above told him that she was doing as she had said she would, and destroying his city.",
  "As he passed under the little gateway which he had built of three dominoes with the little silver knight in armour on the top, he noticed that he was only as high as a domino, and you know how very little that is.",
  "He thought he was walking straight, but really he was turning first this way and then that, and then the other way among the avenues of silver pillars which all looked just alike.",
  "Well, all those people as made the things you made the cities of, they live in the cities and they've made the insides to the houses.",
  "He put on his shirt and knickerbockers again, and wandered round the room looking at the clothes laid out there, and wondering which of the wonderful costumes would be really suitable for a knight to wear at a banquet.",
  "It was not till he saw a group of them standing stiffly together at the end of the hall that he knew they must be the matches with which he had once peopled a city, no other inhabitants being at hand.",
  "The camel and its load were rather a tight fit for the particular gateway that they happened to go out by, and the children had to stoop to avoid scraping their heads against the top of the arch.",
  "But they got through all right, and now they were well on the road which was really little more than a field path running through the flowery meadow country where the dragon had been killed.",
  "Of course you understand that, if you can only make a parrot understand, it can tell you everything you want to know about other animals; because it understands their talk quite naturally and without being made.",
  "But they say that when the government had to make sure that we should always be happy troops of gentle islanders, they decided that the only way was for us to be children.",
  "The whole castle was decorated with garlands of pink and green seaweed like the wreaths that people were wearing, and the whole scene was the gayest and happiest you can imagine.",
  "And the town grew nearer and nearer, and the black streak that was the people of the town began to show white dots that were the people's faces.",
  "It was exactly all that they could wish an island to be; because, of course, they had made it themselves, and of course they knew exactly what they wanted.",
  "The light of the lamps shone ahead on the dark gleaming water, and then quite suddenly it did not shine on the water because there was no longer any water for it to shine on.",
  "Slowly and steadily it came; now it reached the level of the dome, now it hung below it; down, down, down it came, past the level of their eager eyes and splashed in the water close by the ship.",
  "Her assurance that some naughty boy must have come through the window and done it while she was not there convinced nobody, and, indeed, the window was shut and bolted.",
  "There were several things inside: queerlooking instruments, some rather like those in the little box of mathematical instruments that he had had as a prize at school, and some like nothing he had ever seen before.",
  "Then he looked through the glass again; but he found he needed both hands to keep it steady, so he set down the box with the other instruments on the sand at his feet and put the glass to his eye again.",
  "He was surrounded by big stones, and they all seemed to be moving; some were tumbling off others that lay in heaps below them, and others were rolling away from the beach in every direction.",
  "He had never been accustomed to great stones that moved about when no one was touching them, and he looked round for some one to ask how it had happened.",
  "But if the plate didn't get big we could look at the tanner till it covered the plate, and then go on looking and looking and looking and see nothing but the tanner till it was as big as a circus.",
  "It grew out sideways till it touched the walls of the recess, and outwards till it touched the top of the recess, and then it slowly worked out into the big cave and came nearer and nearer to the boys.",
  "And once he fought the grocer's boy and got licked and didn't cry, and made friends with the grocer's boy afterwards, and got him to show him all he knew about fighting, so you see he was really not a mug.",
  "In fact, he rather liked it, with half his mind; but the other half didn't like it, because it meant parting from his mother who, so far, had been his only friend.",
  "Quentin, who had to keep his mouth shut very tight these days, because, of course, a boy of ten cannot cry before other chaps, shut the book he was reading and looked up.",
  "All his grief for his wounded father, his sorrow at the parting from his mother, all his hatred of his school, and his contempt for his schoolfellows went into that blow.",
  "He lifted the sacking at one corner so that he could look out between the canvas of the cart's back and side, and hoped to see the classical master distractedly looking for him.",
  "And he was fed well all the time, and all the time made much of, so that when the ship reached land he was quite sorry.",
  "They were talking it over for the hundredth time on the palace terrace where the pomegranates and oleanders grew in green tubs and the marble balustrade is overgrown with roses, red and white and pink and yellow.",
  "And when she got to the palace and got off her camel and went in, there was a strange king on her father's throne and a strange queen sat in her mother's place at his side.",
  "And instantly she was standing with her hands on a young man's shoulders and her lips on a young man's face just where the hair begins and the forehead leaves off.",
  "He had no more idea how to look for his fortune than you would have if you suddenly left off reading this and went out of your front door to seek yours.",
  "And the lord wrote it all down in a book, and half the people said it was wonderfully clever, and the other half said it was nonsense, and how could he know.",
  "She could not see or hear him, but at the touch of his hand and his lips she knew that he was her heart's lord, and she threw her arms round his neck, and cried more than ever.",
  "This may have been because mother seemed so tired and ill; and gentlemen in black coats and high hats came to see mother, and after they had gone she used to cry.",
  "They hated work, and they were a glum, silent, disagreeable people, but as far as they could be pleased about anything they were pleased to live in bells that were never rung, in houses where there was nothing to do.",
  "Because every now and then she had felt sure that she was really safe in her own bed, and that this was a dream.",
  "It would have done you good to see how the ones who had been rich and crows ran to meet the ones who had been pigeons and poor.",
  "The kids were only two or three years younger than he was, but that is a great deal when you are the elder; and besides, one of the kids was a girl.",
  "Then he tried to climb up the slanting mud and on to the grassy bank, but the grass hurt his fins horribly, and when he put his nose out of the water, the air stifled him, and he was glad to slip back again.",
  "So they took the hurt foot to the hospital, and of course he had to go with it, and the hospital was much more like the heaven he read of in his books than anything he had ever come across before.",
  "Instead he found next day, when his aunt had gone out shopping, a little square of cardboard at the back of the dresser drawer, among the dirty dusters and clothes pegs and string and corks and novelettes.",
  "Dickie thought of the kitchen at home, the lamp that smoked, the dirty table, the fender full of ashes and dirty paper, the dry bread that tasted of mice, and the water out of the broken earthenware cup.",
  "They did not stay there, but walked out across the downs, where the skylarks were singing, and on a dip of the downs came upon great stone walls and towers very strong and gray.",
  "He felt as you would feel if you suddenly found your hands covered with filth, not good honest dirt, but slimy filth, and would not understand how you could have let it get there.",
  "He got out the knife that should have cut the string of the basket in the train, opened it and cut the stalk of the moonflower, very carefully so that none of the seeds should be, and only a few were, lost.",
  "Dickie hardly moved at all, and the chips that fell from his work fell more softly than the twigs and acorns that dropped now and then from some high bough.",
  "And it seemed quite plain to him that if this that had happened to him was not magic, then there never was and never would be any magic to happen to any one.",
  "The box was wrapped in a silk scarf, and the whole packet put into a big earthenware jar with a lid, and the join of lid and jar was smeared with resin and covered with clay.",
  "Dickie put out his rushlight and stayed quiet for a little while, but presently it was impossible to stay quiet another moment, so very softly and carefully he crept out and hid behind a tall press at the end of the passage.",
  "Sometimes it comes to them gradually so that they hardly know when it begins, and leaves them as gradually, like a dream when you wake and stretch yourself.",
  "Only for that you'd have to meet them in your own time that you were born in, and you'll have to wait till it's summer, because that's where they are now.",
  "But you know that now they have used their magic to get back their father, and can no longer use it to look for treasure.",
  "Hands fumbled, his face was cleared of the cloak, and a handkerchief with a round pebble in it was stuffed into his mouth so that he could not speak.",
  "Everyone in the room was looking at the two children, and it seemed impossible for them not to advance, though slowly and shyly, right to the front of the throne.",
  "True followed at the slack chain's end till they got to the milestone, and then suddenly he darted ahead and took the lead, the chain stretched taut, and the boy had all his work cut out to keep up with the dog.",
  "His eyes had got used to the gentle starlight, and he followed the dog among the gorse and brambles without stumbling and without hurting himself against the million sharp spears and thorns.",
  "It turned out that more than one old man in the village had heard from his father about the caves and the smuggling that had gone on in those parts in old ancient days.",
  "Then they all went down to the mound, and the engineer then poked and prodded it and said he should not wonder if they were not so far out.",
  "It was a grand moment when the bricks had been taken out and daylight poured into the cave, and nothing remained but to break down the dam and let the water run out of the darkness into the sunshine.",
  "It was in the courtyard wall, the courtyard that was now a smooth grass lawn and not the rough, daisied grass plot dotted with heaps of broken stone and masonry that they were used to see.",
  "There was mortar or cement at their edges, and when the last stone was replaced no one could tell those stones from the other stones that formed the wall.",
  "The blue sky showed through the archway where the tall gates had been and under the arch was a mass of men shouting, screaming, struggling, and the gleam of steel and the scarlet of brave blood.",
]

export default sentences
